import React, { useRef, useEffect } from 'react';
import { useTimePicker } from '../hooks/useTimePicker';
import AnimatedClock from './AnimatedClock';

const ScrollPicker = ({ values, selected, onChange, formatValue }) => {
    const containerRef = useRef(null);
    const itemHeight = 44;
    const isScrolling = useRef(false);
    const scrollTimeout = useRef(null);

    useEffect(() => {
        if (containerRef.current && !isScrolling.current) {
            const index = values.indexOf(selected);
            if (index !== -1) {
                containerRef.current.scrollTop = index * itemHeight;
            }
        }
    }, [selected, values]);

    const handleScroll = () => {
        isScrolling.current = true;

        if (scrollTimeout.current) {
            clearTimeout(scrollTimeout.current);
        }

        scrollTimeout.current = setTimeout(() => {
            if (containerRef.current) {
                const scrollTop = containerRef.current.scrollTop;
                const index = Math.round(scrollTop / itemHeight);
                const clampedIndex = Math.max(0, Math.min(index, values.length - 1));

                containerRef.current.scrollTo({
                    top: clampedIndex * itemHeight,
                    behavior: 'smooth'
                });

                if (values[clampedIndex] !== selected) {
                    onChange(values[clampedIndex]);
                }
            }
            isScrolling.current = false;
        }, 100);
    };

    const handleItemClick = (value, index) => {
        if (containerRef.current) {
            containerRef.current.scrollTo({
                top: index * itemHeight,
                behavior: 'smooth'
            });
        }
        onChange(value);
    };

    return (
        <div className="scroll-picker-wrapper">
            <div className="scroll-picker-highlight" />
            <div
                className="scroll-picker-container"
                ref={containerRef}
                onScroll={handleScroll}
            >
                <div className="scroll-picker-padding" />
                {values.map((value, index) => (
                    <div
                        key={value}
                        className={`scroll-picker-item ${value === selected ? 'selected' : ''}`}
                        onClick={() => handleItemClick(value, index)}
                    >
                        {formatValue ? formatValue(value) : value}
                    </div>
                ))}
                <div className="scroll-picker-padding" />
            </div>
        </div>
    );
};

const TimeScreen = ({ onNext, isActive, variant = 'classic' }) => {
    const { hour, minute, period, setPeriod, setHour, setMinute, clockRef, hourHandRef, minuteHandRef, getTime } = useTimePicker();

    const handleContinue = () => {
        const time = getTime();
        onNext(time);
    };

    const hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
    const minutes = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55];

    const displayHour = hour === 0 ? 12 : hour;

    return (
        <section id="screen-time" className={`screen ${isActive ? 'active' : ''}`}>
            <div className="screen-content">
                <h2 className="screen-title">When works best for you?</h2>
                <div className="clock-container">
                    {variant === 'animated' ? (
                        <AnimatedClock
                            hour={hour}
                            minute={minute}
                            period={period}
                            onPeriodToggle={() => setPeriod(period === 'AM' ? 'PM' : 'AM')}
                            onHourChange={setHour}
                            onMinuteChange={setMinute}
                        />
                    ) : (
                        <svg
                            ref={clockRef}
                            id="clock"
                            viewBox="0 0 200 200"
                            className="analog-clock"
                        >
                            {/* Clock face */}
                            <circle cx="100" cy="100" r="95" className="clock-face" />
                            <circle cx="100" cy="100" r="90" className="clock-inner" />

                            {/* Hour markers */}
                            <g className="hour-markers">
                                {/* Will be generated by JS */}
                            </g>

                            {/* Clock hands */}
                            <line
                                ref={hourHandRef}
                                id="hour-hand"
                                x1="100"
                                y1="100"
                                x2="100"
                                y2="50"
                                className="clock-hand hour-hand"
                            />
                            <line
                                ref={minuteHandRef}
                                id="minute-hand"
                                x1="100"
                                y1="100"
                                x2="100"
                                y2="30"
                                className="clock-hand minute-hand"
                            />

                            {/* Center dot */}
                            <circle cx="100" cy="100" r="6" className="clock-center" />
                        </svg>
                    )}

                    {/* Time picker section - sits next to clock on desktop */}
                    <div className="time-picker-section">
                        {/* AM/PM Toggle - above the time picker */}
                        <div className="period-toggle">
                            <button
                                className={`period-btn ${period === 'AM' ? 'active' : ''}`}
                                onClick={() => setPeriod('AM')}
                            >
                                AM
                            </button>
                            <button
                                className={`period-btn ${period === 'PM' ? 'active' : ''}`}
                                onClick={() => setPeriod('PM')}
                            >
                                PM
                            </button>
                        </div>

                        {/* Scrollable Time Picker */}
                        <div className="time-picker-scroll">
                            <ScrollPicker
                                values={hours}
                                selected={displayHour}
                                onChange={(val) => setHour(val === 12 ? 0 : val)}
                            />
                            <div className="time-picker-colon">:</div>
                            <ScrollPicker
                                values={minutes}
                                selected={minute}
                                onChange={setMinute}
                                formatValue={(val) => val.toString().padStart(2, '0')}
                            />
                        </div>
                    </div>
                </div>
                <button className="btn btn-primary" id="btn-time-next" onClick={handleContinue}>
                    <span>Continue</span>
                </button>
            </div>
        </section>
    );
};

export default TimeScreen;
